"""describe your change

Revision ID: a8adbe723df6
Revises: 0003_two_factor_recovery_codes
Create Date: 2026-05-18 18:18:17.537773+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'a8adbe723df6'
down_revision: Union[str, Sequence[str], None] = '0003_two_factor_recovery_codes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_path', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('image_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    op.drop_column('users', 'image_path')
    # ### end Alembic commands ###
